language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install

after_success:
  - npm run codecov
  - npm run semantic-release
